<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <PropertyGroup>
        <RootNamespace>Itmo.ObjectOrientedProgramming.Lab5.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\..\Itmo\motp10\src\Application.Abstraction\Application.Abstraction.csproj" />
      <ProjectReference Include="..\..\..\..\Itmo\motp10\src\Application.Contracts\Application.Contracts.csproj" />
      <ProjectReference Include="..\..\..\..\Itmo\motp10\src\Application\Application.csproj" />
      <ProjectReference Include="..\..\..\..\Itmo\motp10\src\Models\Models.csproj" />
      <ProjectReference Include="..\..\src\Labwork5\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="NSubstitute">
        <HintPath>..\..\..\..\.nuget\packages\nsubstitute\5.3.0\lib\net6.0\NSubstitute.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
